apiVersion: apps/v1
kind: Deployment
metadata:
  name: maquinarias-app
  namespace: maquinarias
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maquinarias
  template:
    metadata:
      labels:
        app: maquinarias
    spec:
      containers:
      - name: django
        image: ales33/maquinarias-devops:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: maquinarias-config
        - secretRef:
            name: maquinarias-secret
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maquinarias-secret
              key: DB_PASSWORD
        readinessProbe:
          httpGet:
            path: /ready/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: maquinarias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "maquinariasdb"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maquinarias-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc