apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: maquinarias
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080   # accesible en minikube ip:30080
