apiVersion: v1
kind: ConfigMap
metadata:
  name: maquinarias-config
  namespace: maquinarias
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "maquinariasdb"
  DB_USER: "postgres"