apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: maquinarias
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      - job_name: 'django'
        static_configs:
          - targets: ['django-service:8000']
        metrics_path: '/metrics'

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
